# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6dfcb78885c498fbbd7f05c8651a217f8f0d977d10b7f05c9ab7715c24c357afbb8c02d34738be613f9e8c7c45b4da80afba9b2c1d4616fa0662e5158c06d79

test:
  secret_key_base: 6d0bce310cc889765f4617c3b230280bdabc5fb02843dc08ae47058eb7dee3b8af3262df8f61185499f0ab4d6ca0660bd1e99d585a6b8613912218266c5d072d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
